export interface ProviderDefinition {
  id: string;
  name: string;
  description: string;
  defaultBaseUrl: string;
  format: 'openai-chat' | 'anthropic' | 'google' | 'ollama' | 'custom';
  requiresApiKey: boolean;
  requiresBaseUrl: boolean;
  adapterType: string;
  modelsEndpoint: string;
  nativeModelsUrl?: string;
}

export const PROVIDER_REGISTRY: ProviderDefinition[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    description: 'GPT-4o, GPT-4.1, o3, o4-mini',
    defaultBaseUrl: 'https://api.openai.com/v1',
    format: 'openai-chat',
    requiresApiKey: true,
    requiresBaseUrl: false,
    adapterType: 'openai',
    modelsEndpoint: '/models',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    description: 'Claude Opus 4, Sonnet 4, Haiku 3.5',
    defaultBaseUrl: 'https://api.anthropic.com',
    format: 'anthropic',
    requiresApiKey: true,
    requiresBaseUrl: false,
    adapterType: 'anthropic',
    modelsEndpoint: '/v1/models',
  },
  {
    id: 'google',
    name: 'Google',
    description: 'Gemini 2.5 Pro, Gemini 2.5 Flash',
    defaultBaseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    format: 'openai-chat',
    requiresApiKey: true,
    requiresBaseUrl: false,
    adapterType: 'google',
    modelsEndpoint: '/v1beta/models',
    nativeModelsUrl: 'https://generativelanguage.googleapis.com/v1beta/models',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    description: 'DeepSeek V3, R1',
    defaultBaseUrl: 'https://api.deepseek.com',
    format: 'openai-chat',
    requiresApiKey: true,
    requiresBaseUrl: false,
    adapterType: 'openai',
    modelsEndpoint: '/models',
  },
  {
    id: 'mistral',
    name: 'Mistral',
    description: 'Mistral Large, Medium, Small',
    defaultBaseUrl: 'https://api.mistral.ai/v1',
    format: 'openai-chat',
    requiresApiKey: true,
    requiresBaseUrl: false,
    adapterType: 'mistral',
    modelsEndpoint: '/models',
  },
  {
    id: 'groq',
    name: 'Groq',
    description: 'Ultra-fast inference',
    defaultBaseUrl: 'https://api.groq.com/openai/v1',
    format: 'openai-chat',
    requiresApiKey: true,
    requiresBaseUrl: false,
    adapterType: 'openai',
    modelsEndpoint: '/models',
  },
  {
    id: 'together',
    name: 'Together AI',
    description: 'Open-source models at scale',
    defaultBaseUrl: 'https://api.together.xyz/v1',
    format: 'openai-chat',
    requiresApiKey: true,
    requiresBaseUrl: false,
    adapterType: 'openai',
    modelsEndpoint: '/models',
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    description: 'Fast inference on open models',
    defaultBaseUrl: 'https://api.fireworks.ai/inference/v1',
    format: 'openai-chat',
    requiresApiKey: true,
    requiresBaseUrl: false,
    adapterType: 'openai',
    modelsEndpoint: '/models',
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    description: 'Grok models',
    defaultBaseUrl: 'https://api.x.ai/v1',
    format: 'openai-chat',
    requiresApiKey: true,
    requiresBaseUrl: false,
    adapterType: 'openai',
    modelsEndpoint: '/models',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    description: 'Access 200+ models',
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
    format: 'openai-chat',
    requiresApiKey: true,
    requiresBaseUrl: false,
    adapterType: 'openai',
    modelsEndpoint: '/models',
  },
  {
    id: 'ollama',
    name: 'Ollama',
    description: 'Run models locally',
    defaultBaseUrl: 'http://localhost:11434',
    format: 'ollama',
    requiresApiKey: false,
    requiresBaseUrl: false,
    adapterType: 'ollama',
    modelsEndpoint: '/api/tags',
  },
  {
    id: 'lm-studio',
    name: 'LM Studio',
    description: 'Local model inference GUI',
    defaultBaseUrl: 'http://localhost:1234/v1',
    format: 'openai-chat',
    requiresApiKey: false,
    requiresBaseUrl: false,
    adapterType: 'openai',
    modelsEndpoint: '/models',
  },
  {
    id: 'vllm',
    name: 'vLLM',
    description: 'High-throughput local inference',
    defaultBaseUrl: 'http://localhost:8000/v1',
    format: 'openai-chat',
    requiresApiKey: false,
    requiresBaseUrl: false,
    adapterType: 'openai',
    modelsEndpoint: '/models',
  },
  {
    id: 'custom',
    name: 'Custom Provider',
    description: 'Any OpenAI-compatible endpoint',
    defaultBaseUrl: '',
    format: 'openai-chat',
    requiresApiKey: false,
    requiresBaseUrl: true,
    adapterType: 'openai',
    modelsEndpoint: '/models',
  },
];

export function getProviderDefinition(id: string): ProviderDefinition | undefined {
  return PROVIDER_REGISTRY.find((p) => p.id === id);
}
