export const ErrorCodes = {
  // ================= AUTHENTICATION & SECURITY =================
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',

  // ================= USER & PROFILE =================
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  EMAIL_IN_USE_BY_OTHER: 'EMAIL_IN_USE_BY_OTHER',
  USERNAME_IN_USE_BY_OTHER: 'USERNAME_IN_USE_BY_OTHER',
  UPDATE_PROFILE_FAILED: 'UPDATE_PROFILE_FAILED',

  // ================= OTP & VERIFICATION =================
  EMAIL_VERIFICATION_FAILED: 'EMAIL_VERIFICATION_FAILED',
  EMAIL_NOT_EXIST: 'EMAIL_NOT_EXIST',
  PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED',

  // ================= OAUTH & THIRD PARTY =================
  GOOGLE_LINKING_FAILED: 'GOOGLE_LINKING_FAILED',
  OAUTH_ACCOUNT_CONFLICT: 'OAUTH_ACCOUNT_CONFLICT',

  // ================= WORKSPACE =================
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  WORKSPACE_NAME_EXISTS: 'WORKSPACE_NAME_EXISTS',
  WORKSPACE_ACCESS_DENIED: 'WORKSPACE_ACCESS_DENIED',

  // ================= PROJECT =================
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  PROJECT_NAME_EXISTS: 'PROJECT_NAME_EXISTS',

  // ================= SESSION =================
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',

  // ================= TOOL CONFIG =================
  TOOL_CONFIG_NOT_FOUND: 'TOOL_CONFIG_NOT_FOUND',
  TOOL_CONFIG_EXISTS: 'TOOL_CONFIG_EXISTS',

  // ================= MCP SERVER CONFIG =================
  MCP_SERVER_CONFIG_NOT_FOUND: 'MCP_SERVER_CONFIG_NOT_FOUND',
  MCP_SERVER_CONFIG_EXISTS: 'MCP_SERVER_CONFIG_EXISTS',

  // ================= CUSTOM TOOL CONFIG =================
  CUSTOM_TOOL_CONFIG_NOT_FOUND: 'CUSTOM_TOOL_CONFIG_NOT_FOUND',
  CUSTOM_TOOL_CONFIG_EXISTS: 'CUSTOM_TOOL_CONFIG_EXISTS',

  // ================= KNOWLEDGE =================
  KNOWLEDGE_NOT_FOUND: 'KNOWLEDGE_NOT_FOUND',
  KNOWLEDGE_KEY_EXISTS: 'KNOWLEDGE_KEY_EXISTS',

  // ================= PLUGIN =================
  PLUGIN_NOT_FOUND: 'PLUGIN_NOT_FOUND',
  PLUGIN_ALREADY_INSTALLED: 'PLUGIN_ALREADY_INSTALLED',

  // ================= PROVIDER CONFIG =================
  PROVIDER_API_KEY_REQUIRED: 'PROVIDER_API_KEY_REQUIRED',
  PROVIDER_NOT_FOUND: 'PROVIDER_NOT_FOUND',

  // ================= GENERAL =================
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
} as const;

export type ErrorCodeType = (typeof ErrorCodes)[keyof typeof ErrorCodes];
